kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: appcotest
  namespace: fleet-local
spec:
  repo: https://github.com/alessandro-festa/fleet-examples
  branch: main
  paths:
  - appco
  valuesFiles:
    - values.yaml