kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: "https://github.com/alessandro-festa/demo-test"
  paths:
  - fleet-examples/appco
  values:
    global:
      imagePullSecrets: [ "application-collection" ]
  valuesFiles:
    - values.yaml