global:
  imagePullSecrets:
  - application-collection
image:
  registry: dp.apps.rancher.io
  repository: containers/open-webui
  tag: 0.5.14
  # repository: ghcr.io/open-webui/open-webui
  # tag: 0.5.10
  pullPolicy: IfNotPresent
ollamaUrls:
- http://ollama.suseai.svc.cluster.local:11434
persistence:
  enabled: true
  storageClass: local-path
ollama:
  enabled: true
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.5.7
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  defaultModel: "llama3.2"
  ollama:
    models:
      - "llama3.2"
    gpu:
      enabled: false
      type: 'nvidia'
      number: 1
    persistentVolume:
      enabled: true
      storageClass: local-path
pipelines:
  enabled: True
  persistence:
    storageClass: local-path
ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ollama
  tls: true
extraEnvVars:
- name: DEFAULT_MODELS
  value: "llama3.2"
- name: DEFAULT_USER_ROLE
  value: "user"
- name: WEBUI_NAME
  value: "SUSE AI"
- name: GLOBAL_LOG_LEVEL
  value: INFO
- name: RAG_EMBEDDING_MODEL
  value: "sentence-transformers/all-MiniLM-L6-v2"
- name: VECTOR_DB
  value: "milvus"
- name: MILVUS_URI
  value: http://milvus.suseai.svc.cluster.local:19530