global:
  imagePullSecrets:
  - application-collection
  namespace: suseai
image:
  registry: dp.apps.rancher.io
  repository: containers/open-webui
  tag: 0.5.14
  # repository: ghcr.io/open-webui/open-webui
  # tag: 0.5.10
  pullPolicy: IfNotPresent
ollamaUrls:
- http://ollama.suseai.svc.cluster.local:11434
persistence:
  enabled: true
  storageClass: local-path
milvus:
  enabled: true
## Enable or disable Milvus Cluster mode
cluster:
  enabled: false
  image:
    all:
      registry: dp.apps.rancher.io
      repository: containers/milvus
      tag: 2.4.6
      pullPolicy: IfNotPresent
  extraConfigFiles:
    user.yaml: |+
      #    For example enable rest http for milvus proxy
      #    proxy:
      #      http:
      #        enabled: true
      #      maxUserNum: 100
      #      maxRoleNum: 10
      ##  Enable tlsMode and set the tls cert and key
      #  tls:
      #    serverPemPath: /etc/milvus/certs/tls.crt
      #    serverKeyPath: /etc/milvus/certs/tls.key
      #   common:
      #     security:
      #       tlsMode: 1
  service:
    type: ClusterIP
    port: 19530
    portName: milvus
    nodePort: ""
    annotations: {}
    labels: {}
    ## List of IP addresses at which the Milvus service is available
    ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
    ##
    externalIPs: []
    #   - externalIp1

    # LoadBalancerSourcesRange is a list of allowed CIDR values, which are combined with ServicePort to
    # set allowed inbound rules on the security group assigned to the master load balancer
    loadBalancerSourceRanges:
      - 0.0.0.0/0
      # Optionally assign a known public LB IP
      # loadBalancerIP: 1.2.3.4
ollama:
  enabled: true
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  defaultModel: "exaone-deep:2.4b"
  ollama:
    models:
      - "exaone-deep:2.4b"
    gpu:
      enabled: false
      type: 'nvidia'
      number: 1
    persistentVolume:
      enabled: true
      storageClass: local-path
pipelines:
  enabled: True
  persistence:
    storageClass: local-path
ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ollama
  tls: true
extraEnvVars:
- name: DEFAULT_MODELS
  value: "llama3.2"
- name: DEFAULT_USER_ROLE
  value: "user"
- name: WEBUI_NAME
  value: "SUSE AI"
- name: GLOBAL_LOG_LEVEL
  value: INFO
- name: RAG_EMBEDDING_MODEL
  value: "sentence-transformers/all-MiniLM-L6-v2"
- name: VECTOR_DB
  value: "milvus"
- name: MILVUS_URI
  value: http://milvus.suseai.svc.cluster.local:19530