apiVersion: v1
kind: Service
metadata:
  name: k8s-mcp-service
  namespace: suseai
spec:
  selector:
    app: k8s_mcp
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP # Or ClusterIP if you don't need external access