# This is an example overrides yaml enabling deployment of ollama, open-webui, milvus standalone with local storage. 
# Please update these overrides as needed for your environment.
# This is an example of services deployed in suse-private-ai namespace with suse-gen-ai release name.
global:
  imagePullSecrets:
  - application-collection

open-webui:
  #To learn more about the entries, helm show values oci://dp.apps.rancher.io/charts/open-webui
  enabled: true
  ollamaUrls:
  - http://open-webui-ollama.suseai.svc.cluster.local:11434
  persistence:
    enabled: true
    storageClass: local-path
  pipelines:
    enabled: false
  tika:
    enabled: false
  ingress:
    host: suse-ollama-webui
    enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ollama
  tls: true
service:
  type: NodePort
  nodePort: 31000
  port: 80
  protocol: TCP
  targetPort: 80
  containerPort: 8080
  labels: {}
  loadBalancerClass: ""
  extraEnvVars:
  - name: DEFAULT_MODELS
    value: "gemma3:1b-it-qat"
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: WEBUI_NAME
    value: "SUSE AI"
  - name: GLOBAL_LOG_LEVEL
    value: INFO
  - name: VECTOR_DB
    value: "milvus"
  - name: MILVUS_URI
    value: http://open-webui-milvus.suseai.svc.cluster.local:19530
  ollama:
    enabled: true
    image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
  models:
    pull: 
      - gemma3:1b-it-qat
    #To learn more about the entries, helm show values oci://dp.apps.rancher.io/charts/ollama
    persistentVolume:
      enabled: true
      storageClass: local-path
  milvus:
    enabled: true
    cluster:
      enabled: false
    standalone:
      persistence:
        persistentVolumeClaim:
          storageClass: local-path
  etcd:
    replicaCount: 1
    persistence:
      storageClassName: local-path
  minio:
    mode: standalone
    rootUser: "admin"
    rootPassword: "adminminio"
    persistence:
      storageClass: local-path
      size: 5Gi
    resources:
      requests:
        memory: 1024Mi
  kafka:
    enabled: true
  pytorch:
    enabled: false